export const PAKISTAN_CITIES = [
  "Karachi",
  "Lahore",
  "Faisalabad",
  "Rawalpindi",
  "Gujranwala",
  "Peshawar",
  "Multan",
  "Hyderabad",
  "Islamabad",
  "Quetta",
  "Bahawalpur",
  "Sargodha",
  "Sialkot",
  "Sukkur",
  "Larkana",
  "Sheikhupura",
  "Rahim Yar Khan",
  "Jhang",
  "Dera Ghazi Khan",
  "Gujrat",
  "Sahiwal",
  "Wah Cantonment",
  "Mardan",
  "Kasur",
  "Okara",
  "Mingora",
  "Nawabshah",
  "Chiniot",
  "Kotri",
  "Burewala",
  "Hafizabad",
  "Kohat",
  "Khanewal",
  "Mirpur Khas",
  "Turbat",
  "Muzaffargarh",
  "Abbottabad",
  "Mandi Bahauddin",
  "Dera Ismail Khan",
  "Jacobabad",
  "Nowshera",
  "Khuzdar",
  "Attock",
  "Jhelum",
  "Chaman",
  "Gwadar",
  "Shikarpur",
  "Tando Adam",
  "Khairpur",
  "Dadu",
  "Muzaffarabad",
  "Gilgit",
  "Skardu",
].sort();
